version: '3.9'
services:
  tts-api:
    build:
      context: .
      args:
        speech_speed: ${speech_speed}
        mp_workers: ${mp_workers}
    restart: unless-stopped
    ports:
      - '8080:8080'
      - '8001:8001'