apiVersion: v1
kind: Service
metadata:
  name: tts-api
  namespace: {{.Values.global.namespace}}
  labels:
    component: tts-api
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: api
      protocol: TCP
      port: 8001
      targetPort: 8001
  selector:
    component: tts-api
